version: '1.0'

services:

  mysql-server:
    image: mysql:8-oracle
    mem_limit: 700m
    ports:
      - "3306:3306"
    networks:
      - microservice-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: micro-db
    restart: always
    
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - microservice-network
    restart: always
    
  eureka-server:
    image: ramitchandra/rc/eureka-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - microservice-network
    depends_on:
      mysql-server:
        condition: service_started
    healthcheck:
      test: curl -f http://localhost:8761/ || exit 1
      interval: 20s
      timeout: 10s
      retries: 5

  currency-exchange:
    image: ramitchandra/rc/currency-exchange:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - microservice-network
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:mysql://mysql-server:3306/micro-db
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      
  currency-convertor:
    image: ramitchandra/rc/currency-converter:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - microservice-network
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:mysql://mysql-server:3306/micro-db
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
      
  api-gateway:
    image: ramitchandra/rc/api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - microservice-network
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.DATASOURCE.URL: jdbc:mysql://mysql-server:3306/micro-db
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans

networks:
  microservice-network: